routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([ 'middleware' => 'checkLogin' ], function () {
    //Login
    Route::get('login', LoginController::class.'@getLogin')->name('login');
    Route::post('login', LoginController::class.'@postLogin')->name('postLogin');
});

//Routes that needs a logged in user
Route::group([ 'middleware' => 'auth' ], function () {
    Route::get('/', function () {
        return view('blank');
    });
    //Projects
    Route::resource('projects', ProjectsController::class);
    Route::get('projects-data', ProjectsController::class.'@getData')->name('data-projects');
    //Categories
    Route::resource('categories', CategoryController::class);
    Route::get('data', CategoryController::class.'@getData')->name('data');

    //Login
    Route::get('logout', 'LoginController@logout')->name('logout');

    //Profile Settings
    Route::resource('profile-settings', ProfileSettingsController::class);

});

//Register
Route::get('register', RegisterController::class.'@getRegister')->name('register');
Route::post('register', RegisterController::class.'@postRegister')->name('postRegister');

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Datatables\ProjectsDatatable;
use App\Http\Requests\Projects\AddProjectFormRequest;
use App\Http\Requests\Projects\UpdateProjectFormRequest;
use App\Services\CategoryService;
use App\Services\ProjectService;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Session;
use Yajra\DataTables\DataTables;

class ProjectsController extends Controller
{
    private $categoryService;
    private $projectService;
    private $projectsDatatable;

    /**
     * ProjectsController constructor.
     *
     * @param $categoryService
     */
    public function __construct(CategoryService $categoryService, ProjectService $projectService, ProjectsDatatable $projectsDatatable)
    {
        $this->categoryService = $categoryService;
        $this->projectService= $projectService;
        $this->projectsDatatable=$projectsDatatable;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('projects.list',[
            'title' => 'List Projects'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories= $this->categoryService->getAll();
        return view('projects.add', [
            'title' => Lang::get('projects.add'),
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddProjectFormRequest $request)
    {
        try {
            $this->projectService->save($request);
            Session::flash('success', Lang::get('projects.saved'));

            return redirect()->route('projects.index');
        } catch (\Exception $e) {
            Session::flash('error', Lang::get('projects.error').$e->getMessage());

            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project= $this->projectService->get($id);
        return view('projects.preview', [
            'title' => Lang::get('projects.preview'),
            'project' => $project
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project= $this->projectService->get($id);
        $categories= $this->categoryService->getAll();
        return view('projects.edit', [
            'title' => Lang::get('projects.edit'),
            'project' => $project,
            'categories' => $categories
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProjectFormRequest $request, $id)
    {
        try {
            $this->projectService->update($request,$id);
            Session::flash('success', Lang::get('projects.updated'));
            return redirect()->route('projects.index');
        } catch (\Exception $e) {

            Session::flash('error', Lang::get('projects.error').$e->getMessage());

            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->projectService->delete($id);
            Session::flash('success', Lang::get('projects.deleted'));

            return redirect()->route('projects.index');
        } catch (\Exception $e) {
            Session::flash('error', Lang::get('projects.error').$e->getMessage());

            return redirect()->back();
        }
    }

    public function getData(DataTables $dataTable){

        $project = $this->projectService->getAllForDatatable();

        return $this->projectsDatatable->of($dataTable, $project);
    }
}

resources/views/projects/add.blade.php
@extends('admin.partials.layout')

@section('title',$title)

@section('meta-tags')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('css')
    <link href="{{ asset('/admin/assets/css/plugins/iCheck/custom.css') }}" rel="stylesheet">
    <link href="{{ asset('/admin/assets/css/plugins/select2/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/admin/assets/css/plugins/datapicker/datepicker3.css') }}" rel="stylesheet">
@stop
@section('topbar')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>@lang('projects.projects')</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="#">@lang('projects.dashboard')</a>
                </li>

                <li>
                    <a href="{{route('projects.index')}}">@lang('projects.projects')</a>
                </li>
                <li class="active">
                    <strong>@lang('projects.add_new')</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@stop

@section('content')
    @include('admin.partials.inline_messages')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>@lang('projects.add_new')</h5>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" role="form" id="form" method="POST" action="{{route('projects.store')}}" data-parsley-validate>
                        {!! csrf_field() !!}

                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('projects.name') *</label>

                                <div class="col-sm-10"><input type="text"
                                                              class="form-control" name="name" value="{{old('name')}}" data-parsley-required></div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('projects.description') *</label>

                                <div class="col-sm-10">
                                    <textarea type="text"  name="description" class="form-control" rows="3"  required>{{old('description')}} </textarea>

                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label text-right">@lang('projects.category') *</label>

                                <div class="col-sm-10">
                                    <select class="form-control m-b" name="categories[]" multiple data-parsley-required>
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group " >
                            <div class="row">
                                <label class="col-sm-2 control-label text-right">@lang('projects.start_date') *<br/></label>

                                <div class="col-sm-10">
                                    <div class="input-group date">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control data-picker"   name="start_date" value="{{ old('start_date')}}" data-parsley-mindate="<?php echo date('Y-m-d'); ?>" data-parsley-required>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('projects.status') *</label>

                                <div class="col-sm-10">
                                    <div class="i-checks"><label> <input type="radio" checked="" value="active" name="status"> <i></i> @lang('projects.active') </label></div>
                                    <div class="i-checks"><label> <input type="radio"  value="inactive" name="status"> <i></i> @lang('projects.inactive') </label></div>
                                </div>
                            </div>

                        </div>


                        <div class="form-group">
                            <div class="pull-right" style="padding: 10px 15px;">
                                <button type="submit" class="btn btn-w-m btn-primary">
                                    <span class="glyphicon glyphicon-floppy-disk"></span>@lang('projects.save')
                                </button>
                                <a href="{{route('projects.index')}}">
                                    <button type="button" class="btn btn-w-m btn-danger">
                                        <span class="glyphicon glyphicon-ban-circle"></span> @lang('projects.cancel')
                                    </button>
                                </a>
                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('custom_theme_javascript')
    <script>
        //Validation for start date
        window.ParsleyValidator
            .addValidator('mindate', function (value, requirement) {
                // is valid date?
                var timestamp = Date.parse(value),
                    minTs = Date.parse(requirement);

                return isNaN(timestamp) ? false : timestamp > minTs;
            }, 32)
            .addMessage('en', 'mindate', 'This date should be greater than %s');

        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

            $('select[name="categories[]"]').select2();


        });
        $('body').on('focus',".data-picker", function(){
            $(this).datepicker({
                format: 'yyyy-mm-dd',
                startView: 2,
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true,
                onClose: function () {
                    $(this).parsley().validate();
                }
            });
        });


    </script>
@endsection

@section('js')
    <!-- ICheck -->
    <script src="{{ asset('/admin/assets/js/plugins/iCheck/icheck.min.js') }}"></script>
    <!-- Select2 -->
    <script src="{{ asset('/admin/assets/js/plugins/select2/select2.full.min.js') }}"></script>
    <!-- Data picker -->
    <script src="{{ asset('/admin/assets/js/plugins/datapicker/bootstrap-datepicker.js') }}"></script>
@endsection

resources/views/projects/edit.blade.php
@extends('admin.partials.layout')

@section('title',$title)

@section('meta-tags')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('css')
    <link href="{{ asset('/admin/assets/css/plugins/iCheck/custom.css') }}" rel="stylesheet">
    <link href="{{ asset('/admin/assets/css/plugins/select2/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/admin/assets/css/plugins/datapicker/datepicker3.css') }}" rel="stylesheet">
@stop
@section('topbar')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>@lang('projects.projects')</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="#">@lang('projects.dashboard')</a>
                </li>

                <li>
                    <a href="{{route('projects.index')}}">@lang('projects.projects')</a>
                </li>
                <li class="active">
                    <strong>@lang('projects.add_new')</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@stop

@section('content')
    @include('admin.partials.inline_messages')
    <div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>@lang('projects.add_new')</h5>
            </div>

            <div class="ibox-content">
                <form class="form-horizontal" role="form" id="form" method="POST" action="{{route('projects.update',$project->id)}}" data-parsley-validate>
                    {{ method_field('PUT') }}
                    {!! csrf_field() !!}


                    <div class="form-group">
                        <div class="row">
                            <label class="col-sm-2 control-label">@lang('projects.name') *</label>

                            <div class="col-sm-10"><input type="text"
                                                          class="form-control" name="name" value="{{$project->name}}" data-parsley-required></div>
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-sm-2 control-label">@lang('projects.description') *</label>

                            <div class="col-sm-10">
                                <textarea type="text"  name="description" class="form-control" rows="3"  required>{{$project->description}} </textarea>

                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="row">
                            <label class="col-sm-2 control-label text-right">@lang('projects.category') *</label>

                            <div class="col-sm-10">
                                <select class="form-control m-b" name="categories[]" multiple data-parsley-required>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" @foreach($project->categories as $c) @if($category->id == $c->id)selected="selected" @endif @endforeach>{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group " >
                        <div class="row">
                            <label class="col-sm-2 control-label text-right">@lang('projects.start_date') *<br/></label>

                            <div class="col-sm-10">
                                <div class="input-group date">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control data-picker"   name="start_date" value="{{$project->start_date}}" data-parsley-mindate="<?php echo date('Y-m-d'); ?>" data-parsley-required>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="row">
                            <label class="col-sm-2 control-label">@lang('projects.status') *</label>

                            <div class="col-sm-10">
                                <div class="i-checks"><label> <input type="radio" @if($project->status == 'active') checked @endif value="active" name="status"> <i></i> @lang('projects.active') </label></div>
                                <div class="i-checks"><label> <input type="radio" @if($project->status == 'inactive') checked @endif value="inactive" name="status"> <i></i> @lang('projects.inactive') </label></div>
                            </div>
                        </div>

                    </div>


                    <div class="form-group">
                        <div class="pull-right" style="padding: 10px 15px;">
                            <button type="submit" class="btn btn-w-m btn-primary">
                                <span class="glyphicon glyphicon-floppy-disk"></span>@lang('projects.save')
                            </button>
                            <a href="{{route('projects.index')}}">
                                <button type="button" class="btn btn-w-m btn-danger">
                                    <span class="glyphicon glyphicon-ban-circle"></span> @lang('projects.cancel')
                                </button>
                            </a>
                        </div>

                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

@endsection

@section('custom_theme_javascript')
<script>
    //Validation for start date
    window.ParsleyValidator
        .addValidator('mindate', function (value, requirement) {
            // is valid date?
            var timestamp = Date.parse(value),
                minTs = Date.parse(requirement);

            return isNaN(timestamp) ? false : timestamp > minTs;
        }, 32)
        .addMessage('en', 'mindate', 'This date should be greater than %s');

    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });

        $('select[name="categories[]"]').select2();


    });
    $('body').on('focus',".data-picker", function(){
        $(this).datepicker({
            format: 'yyyy-mm-dd',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true,
            onClose: function () {
                $(this).parsley().validate();
            }
        });
    });


</script>
@endsection

@section('js')
<!-- ICheck -->
<script src="{{ asset('/admin/assets/js/plugins/iCheck/icheck.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('/admin/assets/js/plugins/select2/select2.full.min.js') }}"></script>
<!-- Data picker -->
<script src="{{ asset('/admin/assets/js/plugins/datapicker/bootstrap-datepicker.js') }}"></script>
@endsection

resources/views/projects/list.blade.php
@extends('admin.partials.layout')

@section('title',$title)

@section('meta-tags')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('css')
    <link href="{{ asset('/admin/assets/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@stop
@section('topbar')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>@lang('projects.projects')</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="#">@lang('projects.dashboard')</a>
                </li>

                <li class="active">
                    <strong>@lang('projects.projects')</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@stop

@section('content')
    @include('admin.partials.messages')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <a href="{{route('projects.create')}}" style="color: white;"><button type="button" class="btn btn-w-m btn-primary pull-right" style="margin: 7px 10px;">@lang('projects.add_new')</button></a>

                <div class="ibox-title">
                    <h5>@lang('projects.list_projects')</h5>


                </div>
                <div class="ibox-content">

                    <div class="table-responsive">
                        <table id="projects-datatable" class="table table-striped table-bordered table-hover" >
                            <thead>
                            <tr>
                                <th>@lang('projects.id')</th>
                                <th>@lang('projects.name')</th>
                                <th>@lang('projects.description')</th>
                                <th>@lang('projects.category')</th>
                                <th>@lang('projects.start_date')</th>
                                <th>@lang('projects.status')</th>
                                <th>@lang('projects.actions')</th>
                            </tr>
                            </thead>

                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('custom_theme_javascript')
    <script>
        $(document).ready(function () {
            $('#projects-datatable').DataTable({
                "aoColumnDefs": [{
                    'bSortable': false,
                    'aTargets': [-1]
                }],
                aaSorting: [[0, 'DESC']],
                "oLanguage": {
                    "oPaginate": {
                        "sPrevious": "",
                        "sNext": ""
                    }
                },
                "sDom": '<"dt-panelmenu clearfix"lfr>t<"dt-panelfooter clearfix"ip>',
                serverSide: true,
                processing: true,
                destroy: true,
                render: true,
                columns: [
                    {data: 'id', "defaultContent": "<i>Not set</i>", "bVisible": true},
                    {data: 'name', "defaultContent": "<i>Not set</i>"},
                    {data: 'description', "defaultContent": "<i>Not set</i>"},
                    {data: 'categories[, ].name', "defaultContent": "<i>Not set</i>"},
                    {data: 'start_date', "defaultContent": "<i>Not set</i>"},
                    {data: 'status', "searchable": false, "orderable": false},
                    {data: 'action', "searchable": false, "orderable": false}
                ],
                order: [[ 2, "ASC" ]],
                ajax: '{{route('data-projects')}}'

            });

        });

        // Delete project
        function deleteItem(id) {
            if (window.confirm("Are you sure?")) {
                var delete_url = "{!! route('projects.destroy', ":id") !!}";
                delete_url = delete_url.replace(':id', id);

                $.ajax({
                    url: delete_url,
                    type: 'DELETE',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    success: function (result) {
                        window.location.reload();
                    },
                    error: function (result) {
                        window.location.reload();
                    }
                });
            }
        }
    </script>
@endsection

@section('js')
    <script src="{{ asset('/admin/assets/js/plugins/dataTables/datatables.min.js') }}"></script>
@endsection

resources/views/projects/preview.blade.php
@extends('admin.partials.layout')

@section('title',$title)

@section('meta-tags')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('css')
    <link href="{{ asset('/admin/assets/css/plugins/iCheck/custom.css') }}" rel="stylesheet">
    <link href="{{ asset('/admin/assets/css/plugins/select2/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/admin/assets/css/plugins/datapicker/datepicker3.css') }}" rel="stylesheet">
@stop
@section('topbar')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>@lang('projects.projects')</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="#">@lang('projects.dashboard')</a>
                </li>

                <li>
                    <a href="{{route('projects.index')}}">@lang('projects.projects')</a>
                </li>
                <li class="active">
                    <strong>@lang('projects.preview')</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@stop

@section('content')
    @include('admin.partials.messages')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>@lang('projects.preview')</h5>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" role="form" id="form">


                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('projects.name') *</label>

                                <div class="col-sm-10"><input type="text"
                                                              class="form-control" name="name" value="{{$project->name}}"  readonly></div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('projects.description') *</label>

                                <div class="col-sm-10">
                                    <textarea type="text"  name="description" class="form-control" rows="3"   readonly>{{$project->description}} </textarea>

                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label text-right">@lang('projects.category') *</label>

                                <div class="col-sm-10">
                                    <select class="form-control m-b" name="categories[]" multiple disabled>
                                        @foreach($project->categories as $category)
                                            <option value="{{$category->id}}" selected>{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group " >
                            <div class="row">
                                <label class="col-sm-2 control-label text-right">@lang('projects.start_date') *<br/></label>

                                <div class="col-sm-10">
                                    <div class="input-group date">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control data-picker"   name="start_date" value="{{ $project->start_date}}"  readonly>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('projects.status') *</label>

                                <div class="col-sm-10">
                                    <div class="i-checks"><label> <input type="radio" @if($project->status == 'active') checked @endif value="active" name="status" disabled> <i></i> @lang('projects.active') </label></div>
                                    <div class="i-checks"><label> <input type="radio" @if($project->status == 'inactive') checked @endif value="inactive" name="status" disabled> <i></i> @lang('projects.inactive') </label></div>
                                </div>
                            </div>

                        </div>


                        <div class="form-group">
                            <div class="pull-right" style="padding: 10px 15px;">
                                <a href="{{route('projects.index')}}">
                                    <button type="button" class="btn btn-w-m btn-danger">
                                        <span class="glyphicon glyphicon-ban-circle"></span> @lang('projects.cancel')
                                    </button>
                                </a>
                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('custom_theme_javascript')
    <script>

        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

            $('select[name="categories[]"]').select2();


        });



    </script>
@endsection

@section('js')
    <!-- ICheck -->
    <script src="{{ asset('/admin/assets/js/plugins/iCheck/icheck.min.js') }}"></script>
    <!-- Select2 -->
    <script src="{{ asset('/admin/assets/js/plugins/select2/select2.full.min.js') }}"></script>
    <!-- Data picker -->
    <script src="{{ asset('/admin/assets/js/plugins/datapicker/bootstrap-datepicker.js') }}"></script>
@endsection