routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([ 'middleware' => 'checkLogin' ], function () {
    //Login
    Route::get('login', LoginController::class.'@getLogin')->name('login');
    Route::post('login', LoginController::class.'@postLogin')->name('postLogin');
});

//Routes that needs a logged in user
Route::group([ 'middleware' => 'auth' ], function () {
    Route::get('/', function () {
        return view('blank');
    });
    //Projects
    Route::resource('projects', ProjectsController::class);
    Route::get('projects-data', ProjectsController::class.'@getData')->name('data-projects');
    //Categories
    Route::resource('categories', CategoryController::class);
    Route::get('data', CategoryController::class.'@getData')->name('data');

    //Login
    Route::get('logout', 'LoginController@logout')->name('logout');

    //Profile Settings
    Route::resource('profile-settings', ProfileSettingsController::class);

});

//Register
Route::get('register', RegisterController::class.'@getRegister')->name('register');
Route::post('register', RegisterController::class.'@postRegister')->name('postRegister');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Datatables\CategoriesDatatable;
use App\Http\Requests\Categories\AddCategoryFormRequest;

use App\Http\Requests\Categories\UpdateCategoryFormRequest;
use App\Services\CategoryService;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Session;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{

    private $categoryService;

    private $categoriesDatatable;


    /**
     * CategoryController constructor.
     *
     * @param $categoryService
     */
    public function __construct(CategoryService $categoryService, CategoriesDatatable $categoriesDatatable)
    {
        $this->categoryService = $categoryService;
        $this->categoriesDatatable = $categoriesDatatable;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.list', [
            'title' => Lang::get('categories.list')
        ]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.add', [
            'title' => Lang::get('categories.add')
        ]);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(AddCategoryFormRequest $request)
    {

        try {
            $this->categoryService->save($request);
            Session::flash('success', Lang::get('categories.saved'));

            return redirect()->route('categories.index');
        } catch (\Exception $e) {
            Session::flash('error', Lang::get('categories.error').$e->getMessage());

            return redirect()->back();
        }

    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->categoryService->get($id);

        return view('categories.preview', [
            'title'    => 'Preview',
            'category' => $category
        ]);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryService->get($id);

        return view('categories.edit', [
            'title'    => 'Edit',
            'category' => $category
        ]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryFormRequest $request, $id)
    {
        try {
            $this->categoryService->update($request,$id);
            Session::flash('success', Lang::get('categories.updated'));

            return redirect()->route('categories.index');
        } catch (\Exception $e) {
            Session::flash('error', Lang::get('categories.error').$e->getMessage());

            return redirect()->back();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->categoryService->delete($id);
            Session::flash('success', Lang::get('categories.deleted'));

            return redirect()->route('categories.index');
        } catch (\Exception $e) {
            Session::flash('error', Lang::get('categories.error').$e->getMessage());

            return redirect()->back();
        }
    }


    public function getData(DataTables $dataTable)
    {

        $category = $this->categoryService->getAllForDatatable();

        return $this->categoriesDatatable->of($dataTable, $category);
    }
}

resources/views/categories/add.blade.php
@extends('admin.partials.layout')

@section('title',$title)

@section('meta-tags')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('css')
    <link href="{{ asset('/admin/assets/css/plugins/iCheck/custom.css') }}" rel="stylesheet">
@stop
@section('topbar')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>@lang('categories.categories')</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="#">@lang('categories.dashboard')</a>
                </li>

                <li>
                    <a href="{{route('categories.index')}}">@lang('categories.categories')</a>
                </li>
                <li class="active">
                    <strong>@lang('categories.add_new')</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@stop

@section('content')
    @include('admin.partials.inline_messages')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>@lang('categories.add_new')</h5>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" role="form" method="POST" action="{{route('categories.store')}}" data-parsley-validate>
                        {!! csrf_field() !!}

                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.name') *</label>

                                <div class="col-sm-10"><input type="text" placeholder="@lang('categories.name')"
                                                              class="form-control" name="name" value="{{old('name')}}" data-parsley-required></div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.description') *</label>

                                <div class="col-sm-10">
                                    <textarea type="text"  name="description" class="form-control" rows="3"  required>{{old('description')}} </textarea>

                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.status') *</label>

                                <div class="col-sm-10">
                                    <div class="i-checks"><label> <input type="radio" checked="" value="active" name="status"> <i></i> @lang('categories.active') </label></div>
                                    <div class="i-checks"><label> <input type="radio"  value="inactive" name="status"> <i></i> @lang('categories.inactive') </label></div>
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="pull-right" style="padding: 10px 15px;">
                                <button type="submit" class="btn btn-w-m btn-primary">
                                    <span class="glyphicon glyphicon-floppy-disk"></span>@lang('categories.save')
                                </button>
                                <a href="{{route('categories.index')}}">
                                    <button type="button" class="btn btn-w-m btn-danger">
                                        <span class="glyphicon glyphicon-ban-circle"></span> @lang('categories.cancel')
                                    </button>
                                </a>
                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('custom_theme_javascript')
    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
@endsection

@section('js')
    <!-- ICheck -->
    <script src="{{ asset('/admin/assets/js/plugins/iCheck/icheck.min.js') }}"></script>
@endsection

resources/views/categories/edit.blade.php
@extends('admin.partials.layout')

@section('title',$title)

@section('meta-tags')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('css')
    <link href="{{ asset('/admin/assets/css/plugins/iCheck/custom.css') }}" rel="stylesheet">
@stop
@section('topbar')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>@lang('categories.categories')</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="#">@lang('categories.dashboard')</a>
                </li>

                <li>
                    <a href="{{route('categories.index')}}">@lang('categories.categories')</a>
                </li>
                <li class="active">
                    <strong>@lang('categories.edit')</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@stop

@section('content')
    @include('admin.partials.inline_messages')
    @if(Session::has('error'))
        <div class="alert alert-info">
            <a class="close" data-dismiss="alert">×</a>
            <strong>Heads Up!</strong> {!!Session::get('error')!!}
        </div>
    @endif
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>@lang('categories.edit')</h5>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" role="form" method="POST" action="{{route('categories.update', $category->id)}}" data-parsley-validate>
                        {{ method_field('PUT') }}
                        {!! csrf_field() !!}


                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.name') *</label>

                                <div class="col-sm-10"><input type="text" placeholder="@lang('categories.name')"
                                                              class="form-control" name="name" value="{{$category->name}}" data-parsley-required></div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.description') *</label>

                                <div class="col-sm-10">
                                    <textarea type="text"  name="description" class="form-control" rows="3"  data-parsley-required>{{$category->description}} </textarea>

                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.status') *</label>

                                <div class="col-sm-10">
                                    <div class="i-checks"><label> <input type="radio" @if($category->status == 'active') checked @endif value="active" name="status"> <i></i> @lang('categories.active') </label></div>
                                    <div class="i-checks"><label> <input type="radio"  @if($category->status == 'inactive') checked @endif value="inactive" name="status"> <i></i> @lang('categories.inactive') </label></div>
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="pull-right" style="padding: 10px 15px;">
                                <button type="submit" class="btn btn-w-m btn-primary">
                                    <span class="glyphicon glyphicon-floppy-disk"></span>@lang('categories.save')
                                </button>
                                <a href="{{route('categories.index')}}">
                                    <button type="button" class="btn btn-w-m btn-danger">
                                        <span class="glyphicon glyphicon-ban-circle"></span> @lang('categories.cancel')
                                    </button>
                                </a>
                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('custom_theme_javascript')
    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
@endsection

@section('js')
    <!-- ICheck -->
    <script src="{{ asset('/admin/assets/js/plugins/iCheck/icheck.min.js') }}"></script>
@endsection

resources/views/categories/list.blade.php
@extends('admin.partials.layout')

@section('title',$title)

@section('meta-tags')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('css')
    <link href="{{ asset('/admin/assets/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@stop
@section('topbar')
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@lang('categories.categories')</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">@lang('categories.dashboard')</a>
            </li>

            <li class="active">
                <strong>@lang('categories.categories')</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
    @stop

@section('content')
    @include('admin.partials.messages')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <a href="{{route('categories.create')}}" style="color: white;"><button type="button" class="btn btn-w-m btn-primary pull-right" style="margin: 7px 10px;">@lang('categories.add_new')</button></a>

                <div class="ibox-title">
                    <h5>@lang('categories.list_cat')</h5>


                </div>
                <div class="ibox-content">

                    <div class="table-responsive">
                        <table id="categories-datatable" class="table table-striped table-bordered table-hover" >
                            <thead>
                            <tr>
                                <th>@lang('categories.id')</th>
                                <th>@lang('categories.name')</th>
                                <th>@lang('categories.description')</th>
                                <th>@lang('categories.status')</th>
                                <th>@lang('categories.actions')</th>
                            </tr>
                            </thead>

                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('custom_theme_javascript')
<script>
    $(document).ready(function () {
        $('#categories-datatable').DataTable({
            "aoColumnDefs": [{
                'bSortable': false,
                'aTargets': [-1]
            }],
            aaSorting: [[0, 'DESC']],
            "oLanguage": {
                "oPaginate": {
                    "sPrevious": "",
                    "sNext": ""
                }
            },
            "sDom": '<"dt-panelmenu clearfix"lfr>t<"dt-panelfooter clearfix"ip>',
            serverSide: true,
            processing: true,
            destroy: true,
            render: true,
            columns: [
                {data: 'id', "defaultContent": "<i>Not set</i>", "bVisible": true},
                {data: 'name', "defaultContent": "<i>Not set</i>"},
                {data: 'description', "defaultContent": "<i>Not set</i>"},
                {data: 'status', "searchable": false, "orderable": false},
                {data: 'action', "searchable": false, "orderable": false}
            ],
            order: [[ 2, "ASC" ]],
            ajax: '{{route('data')}}'

        });

    });
    // Delete category
    function deleteItem(id) {
        if (window.confirm("Are you sure?")) {
            var delete_url = "{!! route('categories.destroy', ":id") !!}";
            delete_url = delete_url.replace(':id', id);

            $.ajax({
                url: delete_url,
                type: 'DELETE',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (result) {
                    window.location.reload();
                },
                error: function (result) {
                    window.location.reload();
                }
            });
        }
    }
</script>
@endsection

@section('js')
    <script src="{{ asset('/admin/assets/js/plugins/dataTables/datatables.min.js') }}"></script>
@endsection

resources/views/categories/preview.blade.php
@extends('admin.partials.layout')

@section('title',$title)

@section('meta-tags')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('css')
    <link href="{{ asset('/admin/assets/css/plugins/iCheck/custom.css') }}" rel="stylesheet">
@stop
@section('topbar')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>@lang('categories.categories')</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="#">@lang('categories.dashboard')</a>
                </li>

                <li>
                    <a href="{{route('categories.index')}}">@lang('categories.categories')</a>
                </li>
                <li class="active">
                    <strong>@lang('categories.preview')</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@stop

@section('content')
    @include('admin.partials.messages')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>@lang('categories.preview')</h5>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" role="form" >

                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.name') *</label>

                                <div class="col-sm-10"><input type="text" placeholder="@lang('categories.name')"
                                                              class="form-control" name="name" value="{{$category->name}}" readonly></div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.description') *</label>

                                <div class="col-sm-10">
                                    <textarea type="text"  name="description" class="form-control" rows="3"  readonly>{{$category->description}} </textarea>

                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-2 control-label">@lang('categories.status') *</label>

                                <div class="col-sm-10">
                                    <div class="i-checks"><label> <input type="radio" @if($category->status == 'active') checked @endif value="active" name="status" disabled> <i></i> @lang('categories.active') </label></div>
                                    <div class="i-checks"><label> <input type="radio" @if($category->status == 'inactive') checked @endif value="inactive" name="status" disabled> <i></i> @lang('categories.inactive') </label></div>
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="pull-right" style="padding: 10px 15px;">
                                <a href="{{route('categories.index')}}">
                                    <button type="button" class="btn btn-w-m btn-danger">
                                        <span class="glyphicon glyphicon-ban-circle"></span> @lang('categories.cancel')
                                    </button>
                                </a>
                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('custom_theme_javascript')
    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
@endsection

@section('js')
    <!-- ICheck -->
    <script src="{{ asset('/admin/assets/js/plugins/iCheck/icheck.min.js') }}"></script>
@endsection