routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([ 'middleware' => 'checkLogin' ], function () {
    //Login
    Route::get('login', LoginController::class.'@getLogin')->name('login');
    Route::post('login', LoginController::class.'@postLogin')->name('postLogin');
});

//Routes that needs a logged in user
Route::group([ 'middleware' => 'auth' ], function () {
    Route::get('/', function () {
        return view('blank');
    });
    //Projects
    Route::resource('projects', ProjectsController::class);
    Route::get('projects-data', ProjectsController::class.'@getData')->name('data-projects');
    //Categories
    Route::resource('categories', CategoryController::class);
    Route::get('data', CategoryController::class.'@getData')->name('data');

    //Login
    Route::get('logout', 'LoginController@logout')->name('logout');

    //Profile Settings
    Route::resource('profile-settings', ProfileSettingsController::class);

});

//Register
Route::get('register', RegisterController::class.'@getRegister')->name('register');
Route::post('register', RegisterController::class.'@postRegister')->name('postRegister');

resources/views/admin/partials/datatable_action_column.blade.php
@isset($preview)
    <a class="btn btn-xs btn-success" href="{{ $preview }}" @isset($target) target="{{ $target }}" @endisset><i class="glyphicon glyphicon-eye-open"></i> Preview</a>
@endisset
@isset($edit)
    <a class="btn btn-xs btn-warning" href="{{ $edit }}" @isset($target) target="{{ $target }}" @endisset><i class="glyphicon glyphicon-edit"></i> Edit</a>
@endisset
@isset($delete)
    <a class="btn btn-xs btn-danger" onClick='deleteItem({{ $delete }}, this)' @isset($target) target="{{ $target }}" @endisset><i class="glyphicon glyphicon-remove"></i> Delete</a>
@endisset

resources/views/admin/partials/datatable_status_column.blade.php
<div class="buttons-justify">
    @if($active)
        <span class="badge badge-primary badge-width">Active</span>

    @else
        <span class="badge badge-danger badge-width">Inactive</span>
    @endif
</div>

resources/views/admin/partials/footer.blade.php
<div class="footer">
    <div class="pull-right">

    </div>
    <div>
        <strong>Copyright</strong> Ivana Jakimovska &copy; {{ date('Y') }}
    </div>
</div>

resources/views/admin/partials/inline_messages.blade.php
@if(Session::has('error'))
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-danger alert-dismissible admin_message" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <i class="fa fa-times" aria-hidden="true"></i> <strong>{{ Session::get('error') }}</strong>
            </div>
        </div>
    </div>
@endif

@if (count($errors) > 0)
    <div class="alert alert-danger" style="text-align: center">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <ul>
            @foreach ($errors->all() as $error)
                <li style="list-style-type: none;">{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if(Session::has('info'))
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-primary alert-dismissible admin_message" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <i class="fa fa-info-circle" aria-hidden="true"></i> <strong>{{ Session::get('info') }}</strong>
            </div>
        </div>
    </div>
@endif

@if(Session::has('success'))
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-success alert-dismissible admin_message" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <i class="fa fa-check" aria-hidden="true"></i> <strong>{{ Session::get('success') }}</strong>
            </div>
        </div>
    </div>
@endif

resources/views/admin/partials/layout.blade.php
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>My Team | @yield('title')</title>

    <link rel="icon" type="image/png" href="{{ asset('img/favicon-32x32.png') }}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{{ asset('img/favicon-16x16.png') }}" sizes="16x16" />
    @yield('meta-tags')

    @include('admin.partials.css.global_css')

    @yield('css')

    @include('admin.partials.js.main_js')
</head>

<body>
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
            @include('admin.partials.sidebar_left')
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">

                @include('admin.partials.navbar')

        </div>
        @yield('topbar')

        <div class="wrapper wrapper-content">

                 @yield('content')
        </div>

                 @include('admin.partials.footer')

    </div>
        @include('admin.partials.sidebar_right')
</div>

<div class="loading">Loading&#8230;</div>


<!-- Custom and plugin javascript -->
@include('admin.partials.js.custom_js')

<!-- jQuery UI -->
@include('admin.partials.js.jquery_bottom_page')

@yield('custom_theme_javascript')

@yield('js')
</body>
</html>

resources/views/admin/partials/messages.blade.php
@if(Session::has('error'))
    <script>
        $(document).ready(function(){
            swal({
                title: "Ops!",
                text: "{{ Session::get('error') }}",
                type: "error"
            });
        });
    </script>
@endif

@if (count($errors) > 0)
    <script>
        $(document).ready(function(){
            swal({
                title: "Ops!",
                html: '{!! implode(" <br>",$errors->all()) !!}',
                type: "error"
            });
        });
    </script>
@endif

@if(Session::has('info'))
    <script>
        $(document).ready(function(){
            swal({
                title: "Ops!",
                html: '{{ Session::get('info') }}',
                type: "info"
            });
        });
    </script>
@endif

@if(Session::has('success'))
    <script>
        $(document).ready(function(){
            swal({
                title: "Good job!",
                text: "{{ Session::get('success') }}",
                type: "success",
                timer: 2000
            });
        });
    </script>
@endif

resources/views/admin/partials/navbar.blade.php
<nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        <form role="search" class="navbar-form-custom" action="#">
            <div class="form-group">

            </div>
        </form>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li>
            <a href="{{route('logout')}}">
                <i class="fa fa-sign-out"></i> Log out
            </a>
        </li>
    </ul>

</nav>

resources/views/admin/partials/sidebar_left.blade.php
<div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
        <li class="nav-header">
            <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="{{ asset('/admin/assets/img/user_default.png') }}" />
                             </span>
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{Auth::user()->name}}</strong>
                             </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span> </span> </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                    <li><a href="{{route('profile-settings.index')}}">Profile</a></li>

                    <li class="divider"></li>
                    <li><a href="{{route('logout')}}">Logout</a></li>
                </ul>
            </div>
            <div class="logo-element">
                MT
            </div>
        </li>
        <li class="@if(Request::segment(1) == 'projects') active @endif">
            <a href="{{route('projects.index')}}"><i class="fa fa-bullhorn"></i> <span class="nav-label">Project Management</span></a>
        </li>
        <li class="@if(Request::segment(1) == 'categories') active @endif">
            <a href="{{route('categories.index')}}"><i class="fa fa-bullhorn"></i> <span class="nav-label">Categories</span></a>
        </li>

    </ul>
</div>